#!/bin/sh
set -euf

mkdir -p /opt/updatecommand
cd /opt/updatecommand
git clone --depth 1 https://github.com/UpdateCommand/update

mkdir -p /opt/gitalias
cd /opt/gitalias
git clone --depth 1 https://github.com/GitAlias/gitalias

mkdir -p /opt/sixarm && cd /opt/sixarm
git clone --depth 1 https://github.com/SixArm/airport-ssid
git clone --depth 1 https://github.com/SixArm/change-case
git clone --depth 1 https://github.com/SixArm/column-tsv
git clone --depth 1 https://github.com/SixArm/gettimeofday-localtime
git clone --depth 1 https://github.com/SixArm/gitconfig
git clone --depth 1 https://github.com/SixArm/gpg-decrypt
git clone --depth 1 https://github.com/SixArm/gpg-encrypt
git clone --depth 1 https://github.com/SixArm/log-file-cleaning
git clone --depth 1 https://github.com/SixArm/pandoc-from-markdown-into-pdf-with-favorites
git clone --depth 1 https://github.com/SixArm/pmset-scripts
git clone --depth 1 https://github.com/SixArm/port-to-process
git clone --depth 1 https://github.com/SixArm/rsync-mirror
git clone --depth 1 https://github.com/SixArm/random-ascii
git clone --depth 1 https://github.com/SixArm/random-hex
git clone --depth 1 https://github.com/SixArm/sixarm-password
git clone --depth 1 https://github.com/SixArm/ssh-keygen-pro
git clone --depth 1 https://github.com/SixArm/tmux-start
git clone --depth 1 https://github.com/SixArm/sixarm_apt_scripts
git clone --depth 1 https://github.com/SixArm/sixarm_dpkg_builder
git clone --depth 1 https://github.com/SixArm/sixarm_dpkg_scripts
git clone --depth 1 https://github.com/SixArm/sixarm_gem_scripts
git clone --depth 1 https://github.com/SixArm/sixarm_html_scripts
git clone --depth 1 https://github.com/SixArm/sixarm_htx
git clone --depth 1 https://github.com/SixArm/sixarm_markdown_scripts
git clone --depth 1 https://github.com/SixArm/sixarm_mysql_scripts
git clone --depth 1 https://github.com/SixArm/sixarm_postgresql_scripts
git clone --depth 1 https://github.com/SixArm/sixarm_ruby_gem_scripts
git clone --depth 1 https://github.com/SixArm/sixarm_ruby_gemforge
git clone --depth 1 https://github.com/SixArm/sixarm_shell_random_scripts
git clone --depth 1 https://github.com/SixArm/sixarm_shell_statistics
git clone --depth 1 https://github.com/SixArm/sixarm_ssh_scripts
git clone --depth 1 https://github.com/SixArm/sixarm_unix_environment
git clone --depth 1 https://github.com/SixArm/sixarm_unix_shell_scripts
git clone --depth=1 https://github.com/SixArm/sixarm-zsh-config.git
