#!/bin/sh
set -euf

mkdir -p /opt/updatecommand
cd /opt/updatecommand && git clone --depth 1 https://github.com/UpdateCommand/update /opt/updatecommand

mkdir -p /opt/gitalias
cd /opt/gitalias && git clone --depth 1 https://github.com/GitAlias/gitalias 

mkdir -p /opt/sixarm
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/airport-ssid
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/apt-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/change-case
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/column-tsv
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/dpkg-builder
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/dpkg-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/gem-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/gettimeofday-localtime
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/git-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/gitconfig-settings
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/github-api-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/gpg-decrypt
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/gpg-encrypt
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/html-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/htx
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/log-file-cleaning
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/markdown-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/mysql-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/pmset-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/port-to-process
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/posix-shell-script-kit
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/postgresql-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/random-ascii
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/random-hex
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/rename-to-date-time-slug
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/rsync-mirror
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/ruby-gemforge
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/shell-random-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/shell-statistics
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/sixarm-password
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/ssh-keygen-pro
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/ssh-scripts
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/ssid-powerful
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/symlink-index-md-to-readme-md
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/tmux-start
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/tmux-start-rails
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/unix-environment
cd /opt/sixarm && git clone --depth 1 https://github.com/SixArm/unix-shell-scripts
cd /opt/sixarm && git clone --depth=1 https://github.com/SixArm/curl-chatgpt
cd /opt/sixarm && git clone --depth=1 https://github.com/SixArm/html-span-data-chatgpt-prompt
cd /opt/sixarm && git clone --depth=1 https://github.com/SixArm/pandoc-from-markdown-to-pdf
cd /opt/sixarm && git clone --depth=1 https://github.com/SixArm/zsh-config